/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const GdsAccessibility: typeof import('gdsi/vanilla.js')['AccessibilityIcon']
  const GdsZeroConfig: typeof import('gdsi/vanilla.js')['ZeroConfigIcon']
}
