/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const GdsZeroConfig: typeof import('gdsi/svg/zero-config')['ZeroConfigIcon']
}
