packages:
  - examples/*
  - packages/*
  - docs


catalog:
  '@types/react': ^18.3.1
  fast-glob: ^3.3.2
  unbuild: ^3.5.0
  unplugin-auto-import: ^0.19.0
  unplugin-vue-components: ^0.28.0
  mkdist: ^2.3.0
  vue: ^3.5.13
  typescript: ^5.7.2
  react: ^18.3.1
