packages:
  - examples/*
  - packages/*
  - docs

catalog:
  '@types/react': ^18.3.23
  fast-glob: ^3.3.3
  unbuild: ^3.6.1
  unplugin-auto-import: ^0.19.0
  unplugin-vue-components: ^0.28.0
  mkdist: ^2.3.0
  vue: ^3.5.19
  typescript: ^5.9.2
  react: ^18.3.1
