/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconZeroConfig: typeof import('@gdsicon/react/zero-config')['default']
  const ZeroConfigIcon: typeof import('gdsi/react/zero-config')['default']
  const ZeroConfigIconAS: typeof import('gdsi/react/zero-config')['ZeroConfigIcon']
}
